# Import data from Conflicted Glossary

In [1]:
import pandas as pd

# Load the CSV files into DataFrames
codes_df = pd.read_csv('../_temp/glossary.csv')  # type: ignore
elements_df = pd.read_csv('../_temp/transcripts.csv')  # type: ignore

# Rename columns according to the provided mapping
codes_df = codes_df.rename(columns={
    'Glossary ID': 'code_id',
    'Term': 'term',
    'Description': 'description',
    'Type': 'type',
    'Read more': 'reference',
    'Lat/Long': 'coordinates'
})

elements_df = elements_df.rename(columns={
    'Text ID': 'element_id',
    'Text': 'element_text',
    'Episode ID': 'segment_id',
    'Episode': 'segment_title',
    'Glossary IDs': 'code_ids'
})
# drop the columns that are not element_id, element_text, segment_id, segment_title, code_ids
elements_df = elements_df[['element_id', 'element_text', 'segment_id', 'segment_title', 'code_ids']]

elements_df['code_ids'] = elements_df['code_ids'].fillna('') # type: ignore

# remove any rows in the elements_df where the element_text is empty
elements_df = elements_df[elements_df['element_text'].notnull()]

# create a dataframe with all unique segment_id and segment_title
segment_df = elements_df[['segment_id', 'segment_title']].drop_duplicates()

# create a dataframe series_df with autoincrementing column series_id and series_title and add one row with series_title = 'Conflicted Podcast'
series_df = pd.DataFrame({'series_id': [1], 'series_title': ['Conflicted Podcast']})

# add a column series_id to the segment_df dataframe and set the value to 1 for all rows
segment_df['series_id'] = 1

# create a dataframe with all unique glossary type
code_type_df = codes_df[['type']].drop_duplicates()
# rename the column to type_name
code_type_df = code_type_df.rename(columns={'type': 'type_name'})
# create an incrementing type_id column
code_type_df['type_id'] = range(1, len(code_type_df) + 1)

# Create a column type_id in the codes_df dataframe and map the type_name to the type_id
# Merge the code_type_df with the codes_df on type = type_name
codes_df = codes_df.merge(code_type_df, left_on='type', right_on='type_name', how='left') # type: ignore
codes_df = codes_df.rename(columns={'type_name': 'type_id'})
codes_df = codes_df[['code_id', 'term', 'description', 'type_id', 'reference', 'coordinates']]

In [2]:
# create a dataframe project_df with autoincrementing column project_id and project_title and projcet_description and add one row with project_title = 'Conflicted Glossary' and project_description = 'Glossary for the Conflicted Podcast'
project_df = pd.DataFrame({'project_id': [1], 'project_title': ['Conflicted Glossary'], 'project_description': ['Glossary for the Conflicted Podcast']})

# Add a column project_id to the codes_df dataframe and set the value to 1 for all rows
codes_df['project_id'] = 1

# Add a column project_id to the code_type_df dataframe and set the value to 1 for all rows
code_type_df['project_id'] = 1

# Add a column project_id to the elements_df dataframe and set the value to 1 for all rows
elements_df['project_id'] = 1

# Add a column project_id to the segment_df dataframe and set the value to 1 for all rows
segment_df['project_id'] = 1

# Add a column project_id to the series_df dataframe and set the value to 1 for all rows
series_df['project_id'] = 1

In [3]:
# Create a new DataFrame annotations_df with columns element_id, code_id
annotations_df = pd.DataFrame(columns=['element_id', 'code_id'])

# Iterate over each row in elements_df and add rows to annotations_df
rows_to_add = []
for index, row in elements_df.iterrows():
    element_id = row['element_id']
    code_ids = row['code_ids'].split(';')
    for code_id in code_ids if code_ids != [''] else []:
        code_id = int(code_id)
        rows_to_add.append({'element_id': element_id, 'code_id': code_id})

elements_df.drop(columns=['code_ids', 'segment_title'], inplace=True) # type: ignore

# Convert list of rows to DataFrame and concatenate
annotations_df = pd.concat([annotations_df, pd.DataFrame(rows_to_add)], ignore_index=True)

# Convert code_id to int
annotations_df['code_id'] = annotations_df['code_id'].astype(int)

# Add a column annotation_id to annotations_df
annotations_df['annotation_id'] = annotations_df.index

# Add a column project_id to the annotations_df dataframe and set the value to 1 for all rows
annotations_df['project_id'] = 1

# Define Database

In [4]:
from kanot.db.schema import create_database, drop_database, Project, CodeType, Code, Series, Segment, Element, Annotation
from sqlalchemy import create_engine, Engine
from sqlalchemy.orm import sessionmaker

# Create a connection to the SQLite database
engine: Engine = create_engine('sqlite:///../local_database.db', echo=True)
MySession = sessionmaker(bind=engine)
session = MySession()

drop = True
if drop:
    # Drop all the tables in the database
    drop_database(engine)

# Create the tables in the database
create_database(engine)

2024-07-25 20:39:20,540 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-25 20:39:20,541 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("projects")
2024-07-25 20:39:20,541 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,542 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("code_types")
2024-07-25 20:39:20,543 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,543 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("codes")
2024-07-25 20:39:20,543 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,544 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("series")
2024-07-25 20:39:20,544 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,545 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("segments")
2024-07-25 20:39:20,545 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,545 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("elements")
2024-07-25 20:39:20,545 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,546 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("annotations")
2024-07-25 20:39:20,546 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,546 INFO sqlalchemy.engine.Engine
DROP TABLE annotations
2024-07-25 20:39:20,547 INFO sqlalchemy.engine.Engine [no key 0.00038s] ()
2024-07-25 20:39:20,548 INFO sqlalchemy.engine.Engine
DROP TABLE elements
2024-07-25 20:39:20,549 INFO sqlalchemy.engine.Engine [no key 0.00028s] ()
2024-07-25 20:39:20,549 INFO sqlalchemy.engine.Engine
DROP TABLE segments
2024-07-25 20:39:20,550 INFO sqlalchemy.engine.Engine [no key 0.00021s] ()
2024-07-25 20:39:20,550 INFO sqlalchemy.engine.Engine
DROP TABLE codes
2024-07-25 20:39:20,551 INFO sqlalchemy.engine.Engine [no key 0.00017s] ()
2024-07-25 20:39:20,551 INFO sqlalchemy.engine.Engine
DROP TABLE series
2024-07-25 20:39:20,551 INFO sqlalchemy.engine.Engine [no key 0.00014s] ()
2024-07-25 20:39:20,552 INFO sqlalchemy.engine.Engine
DROP TABLE code_types
2024-07-25 20:39:20,552 INFO sqlalchemy.engine.Engine [no key 0.00014s] ()
2024-07-25 20:39:20,553 INFO sqlalchemy.engine.Engine
DROP TABLE projects
2024-07-25 20:39:20,553 INFO sqlalchemy.engine.Engine [no key 0.00024s] ()
2024-07-25 20:39:20,554 INFO sqlalchemy.engine.Engine COMMIT
2024-07-25 20:39:20,554 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-25 20:39:20,554 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("projects")
2024-07-25 20:39:20,555 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,555 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("projects")
2024-07-25 20:39:20,556 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,556 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("code_types")
2024-07-25 20:39:20,556 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,556 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("code_types")
2024-07-25 20:39:20,557 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,557 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("codes")
2024-07-25 20:39:20,557 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,557 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("codes")
2024-07-25 20:39:20,558 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,558 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("series")
2024-07-25 20:39:20,558 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,559 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("series")
2024-07-25 20:39:20,559 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,559 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("segments")
2024-07-25 20:39:20,559 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,559 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("segments")
2024-07-25 20:39:20,560 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,560 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("elements")
2024-07-25 20:39:20,560 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,560 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("elements")
2024-07-25 20:39:20,560 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,561 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("annotations")
2024-07-25 20:39:20,561 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,561 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("annotations")
2024-07-25 20:39:20,561 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-07-25 20:39:20,562 INFO sqlalchemy.engine.Engine
CREATE TABLE projects (
	project_id INTEGER NOT NULL,
	project_title TEXT NOT NULL,
	project_description TEXT,
	PRIMARY KEY (project_id)
)


2024-07-25 20:39:20,562 INFO sqlalchemy.engine.Engine [no key 0.00019s] ()
2024-07-25 20:39:20,563 INFO sqlalchemy.engine.Engine
CREATE TABLE code_types (
	type_id INTEGER NOT NULL,
	type_name TEXT NOT NULL,
	project_id INTEGER,
	PRIMARY KEY (type_id),
	UNIQUE (type_name),
	FOREIGN KEY(project_id) REFERENCES projects (project_id)
)


2024-07-25 20:39:20,563 INFO sqlalchemy.engine.Engine [no key 0.00038s] ()
2024-07-25 20:39:20,564 INFO sqlalchemy.engine.Engine
CREATE TABLE series (
	series_id INTEGER NOT NULL,
	series_title TEXT NOT NULL,
	project_id INTEGER,
	PRIMARY KEY (series_id),
	FOREIGN KEY(project_id) REFERENCES projects (project_id)
)


2024-07-25 20:39:20,565 INFO sqlalchemy.engine.Engine [no key 0.00019s] ()
2024-07-25 20:39:20,565 INFO sqlalchemy.engine.Engine
CREATE TABLE codes (
	code_id INTEGER NOT NULL,
	term TEXT NOT NULL,
	description TEXT,
	type_id INTEGER,
	reference TEXT,
	coordinates TEXT,
	project_id INTEGER,
	PRIMARY KEY (code_id),
	UNIQUE (term),
	FOREIGN KEY(type_id) REFERENCES code_types (type_id),
	FOREIGN KEY(project_id) REFERENCES projects (project_id)
)


2024-07-25 20:39:20,566 INFO sqlalchemy.engine.Engine [no key 0.00019s] ()
2024-07-25 20:39:20,566 INFO sqlalchemy.engine.Engine
CREATE TABLE segments (
	segment_id INTEGER NOT NULL,
	segment_title TEXT NOT NULL,
	series_id INTEGER,
	project_id INTEGER,
	PRIMARY KEY (segment_id),
	UNIQUE (segment_title),
	FOREIGN KEY(series_id) REFERENCES series (series_id),
	FOREIGN KEY(project_id) REFERENCES projects (project_id)
)


2024-07-25 20:39:20,567 INFO sqlalchemy.engine.Engine [no key 0.00023s] ()
2024-07-25 20:39:20,567 INFO sqlalchemy.engine.Engine
CREATE TABLE elements (
	element_id INTEGER NOT NULL,
	element_text TEXT NOT NULL,
	segment_id INTEGER,
	project_id INTEGER,
	PRIMARY KEY (element_id),
	FOREIGN KEY(segment_id) REFERENCES segments (segment_id),
	FOREIGN KEY(project_id) REFERENCES projects (project_id)
)


2024-07-25 20:39:20,567 INFO sqlalchemy.engine.Engine [no key 0.00018s] ()
2024-07-25 20:39:20,568 INFO sqlalchemy.engine.Engine
CREATE TABLE annotations (
	annotation_id INTEGER NOT NULL,
	element_id INTEGER,
	code_id INTEGER,
	project_id INTEGER,
	PRIMARY KEY (annotation_id),
	CONSTRAINT _element_code_uc UNIQUE (element_id, code_id),
	FOREIGN KEY(element_id) REFERENCES elements (element_id),
	FOREIGN KEY(code_id) REFERENCES codes (code_id),
	FOREIGN KEY(project_id) REFERENCES projects (project_id)
)


2024-07-25 20:39:20,568 INFO sqlalchemy.engine.Engine [no key 0.00018s] ()
2024-07-25 20:39:20,569 INFO sqlalchemy.engine.Engine COMMIT

In [5]:
from sqlalchemy import func
from sqlalchemy.orm import Session
from sqlalchemy.ext.declarative import DeclarativeMeta
from sqlalchemy.exc import IntegrityError
from typing import Any, Hashable

# Define a function to insert data from a DataFrame
def insert_data(df: pd.DataFrame, model: DeclarativeMeta, session: Session) -> None:
    data: list[dict[Hashable, Any]] = df.to_dict(orient='records') # type: ignore
    
    try:
        session.bulk_insert_mappings(model, data) # type: ignore
        session.commit()
    except IntegrityError as e:
        print(f"Unique constraint violation: {e}")
        session.rollback()

# Insert data into the projects table
insert_data(project_df, Project, session)

# Insert data into the code_types table
insert_data(code_type_df, CodeType, session)

# Insert data into the codes table
insert_data(codes_df, Code, session)

# Insert data into the series table
insert_data(series_df, Series, session)

# Insert data into the segments table
insert_data(segment_df, Segment, session)

# Insert data into the elements table
insert_data(elements_df, Element, session)

# Insert data into the annotations table
insert_data(annotations_df, Annotation, session)

# Close the session
session.close()

2024-07-25 20:39:20,617 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-25 20:39:20,619 INFO sqlalchemy.engine.Engine INSERT INTO projects (project_id, project_title, project_description) VALUES (?, ?, ?)
2024-07-25 20:39:20,619 INFO sqlalchemy.engine.Engine [generated in 0.00052s] (1, 'Conflicted Glossary', 'Glossary for the Conflicted Podcast')
2024-07-25 20:39:20,620 INFO sqlalchemy.engine.Engine COMMIT
2024-07-25 20:39:20,622 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-25 20:39:20,623 INFO sqlalchemy.engine.Engine INSERT INTO code_types (type_id, type_name, project_id) VALUES (?, ?, ?)
2024-07-25 20:39:20,623 INFO sqlalchemy.engine.Engine [generated in 0.00035s] [(1, 'Person', 1), (2, 'Events and Periods', 1), (3, 'Group', 1), (4, 'Concept: Cultural and Societal', 1), (5, 'Geography', 1), (6, 'Concept: Political and Social', 1), (7, 'Concept: Economics and Infrastructure', 1), (8, 'Concept: Terrorism and Security', 1)  ... displaying 10 of 16 total bound parameter sets ...  (15, 'Education and Institutions', 1), (16, 'Concept: Legal', 1)]
2024-07-25 20:39:20,624 INFO sqlalchemy.engine.Engine COMMIT
2024-07-25 20:39:20,626 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-25 20:39:20,628 INFO sqlalchemy.engine.Engine INSERT INTO codes (code_id, term, description, type_id, reference, coordinates, project_id) VALUES (?, ?, ?, ?, ?, ?, ?)
2024-07-25 20:39:20,628 INFO sqlalchemy.engine.Engine [generated in 0.00092s] [(875, 'Zelimkhan Yandarbiyev', 'A Chechen writer and politician who served as President of the Chechen Republic of Ichkeria', 1, 'https://en.wikipedia.org/wiki/Zelimkhan_Yandarbiyev', nan, 1), (338, "Zarqawi's cause", 'Referring to the jihadist campaign led by Abu Musab al-Zarqawi, the leader of al-Qaeda in Iraq during the Iraq War.', 1, 'https://en.wikipedia.org/wiki/Abu_Musab_al-Zarqawi', nan, 1), (837, 'Yugoslavia', 'A historical country in Southeastern and Central Europe for most of the 20th century, until its dissolution in the early 1990s.', 2, 'https://en.wikipedia.org/wiki/Yugoslavia', nan, 1), (618, "YPG (People's Protection Units)", 'A Kurdish militia in Syria that controls a portion of Syrian territory and fought against ISIS.', 3, 'https://en.wikipedia.org/wiki/People%27s_Protection_Units', nan, 1), (434, 'Yemeni Tribalism', "The strong tribal culture within Yemen that significantly influences the country's social and political dynamics.", 4, 'https://en.wikipedia.org/wiki/Yemeni_Crisis_(2011–present)', nan, 1), (444, 'Yemeni Sectarian Landscape', 'The religious and sectarian divisions within Yemen, including various Islamic sects such as Sunnis, Zaidis, and Jarudi Zaidis.', 4, 'https://en.wikipedia.org/wiki/Religion_in_Yemen', nan, 1), (503, 'Yemeni Coast', 'The coastline of Yemen, which is strategically important due to its proximity to key shipping routes and the Bab-el-Mandeb Strait.', 5, 'https://en.wikipedia.org/wiki/Geography_of_Yemen', '14.4990, 46.3666', 1), (440, 'Yemeni AK-47 Culture', 'The widespread possession and cultural significance of AK-47s among civilians in Yemen.', 4, 'https://en.wikipedia.org/wiki/Yemeni_Crisis_(2011–present)', nan, 1)  ... displaying 10 of 422 total bound parameter sets ...  (913, '2008 Financial Crisis', 'A severe worldwide economic crisis that occurred in the late 2000s, related to the subprime mortgage market and financial instruments like derivatives.', 2, 'https://en.wikipedia.org/wiki/Financial_crisis_of_2007%E2%80%932008', nan, 1), (64, '9/11', 'A series of coordinated terrorist attacks by the Islamist terrorist group al-Qaeda against the United States on the morning of Tuesday, September 11, 2001.', 8, 'https://en.wikipedia.org/wiki/September_11_attacks', nan, 1)]
2024-07-25 20:39:20,631 INFO sqlalchemy.engine.Engine COMMIT
2024-07-25 20:39:20,633 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-25 20:39:20,633 INFO sqlalchemy.engine.Engine INSERT INTO series (series_id, series_title, project_id) VALUES (?, ?, ?)
2024-07-25 20:39:20,633 INFO sqlalchemy.engine.Engine [generated in 0.00032s] (1, 'Conflicted Podcast', 1)
2024-07-25 20:39:20,634 INFO sqlalchemy.engine.Engine COMMIT
2024-07-25 20:39:20,636 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-25 20:39:20,637 INFO sqlalchemy.engine.Engine INSERT INTO segments (segment_id, segment_title, series_id, project_id) VALUES (?, ?, ?, ?)
2024-07-25 20:39:20,637 INFO sqlalchemy.engine.Engine [generated in 0.00038s] [(1, 'S1E1 - 9/11', 1, 1), (2, 'S1E2 - War on Terror', 1, 1), (3, 'S1E3 - Iraq', 1, 1), (4, 'S1E4 - Yemen', 1, 1), (5, 'S1E5 - Syria', 1, 1), (6, 'S1E6 - Returning Jihadists', 1, 1), (7, 'S2E1 - World War Iran', 1, 1), (8, 'S2E2 - New World Order', 1, 1)  ... displaying 10 of 51 total bound parameter sets ...  (50, "S4E18: Hezbollah: Israel's Menace or Lebanon's Defender?", 1, 1), (51, 'S4E19: Yemen: In the Shadow of the Imam', 1, 1)]
2024-07-25 20:39:20,638 INFO sqlalchemy.engine.Engine COMMIT
2024-07-25 20:39:20,650 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-25 20:39:20,706 INFO sqlalchemy.engine.Engine INSERT INTO elements (element_id, element_text, segment_id, project_id) VALUES (?, ?, ?, ?)
2024-07-25 20:39:20,706 INFO sqlalchemy.engine.Engine [generated in 0.01214s] [(7, "Thomas Small Let's get into it. ", 1, 1), (8, "We'll start this series with an event that catapulted the conflicts of the Middle East into the global consciousness: The Twin Tower attacks on September 11th. ", 1, 1), (9, 'Aimen Dean Okay.', 1, 1), (10, "Thomas Small Right. So, we're just starting. ", 1, 1), (11, 'Aimen Dean Yeah. Go ahead.', 1, 1), (12, "Thomas Small Aimen Dean. How do I introduce Aimen Dean? There is literally no one on Planet Earth like Aimen Dean. Saudi-born, but Bahraini nationali ... (904 characters truncated) ... s his former al-Qaeda – the surviving former al-Qaeda jihadists and their followers want to kill him dead for stabbing them in the back. Aimen Dean. ", 1, 1), (13, 'Aimen Dean Well, that was, you know, a rather ominous introduction. Well, Thomas, how am I going to introduce you? Even after years of knowing you—po ... (715 characters truncated) ... e nuances, the… Understand the Bedouin culture?\' You know, if I want to describe Thomas Small in few words, I would say that he is no small at all. ', 1, 1), (14, "Thomas Small Well, here's the thing, Aimen. I met you and I felt weirdly like I had met some kind of spiritual brother.", 1, 1)  ... displaying 10 of 12396 total bound parameter sets ...  (15609, 'There you will find other fans of the show engaging in heated debates, enlightening conversations, and just generally geeking out over Conflicted related topics.', 51, 1), (15610, 'Conflicted is a Message Heard production. This episode was produced and edited by Harry Stott. Sandra Ferrari is our executive producer. Our theme music is by Matt Huxley and Tom Biddle.', 51, 1)]
2024-07-25 20:39:20,727 INFO sqlalchemy.engine.Engine COMMIT
2024-07-25 20:39:20,735 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-25 20:39:20,747 INFO sqlalchemy.engine.Engine INSERT INTO annotations (annotation_id, element_id, code_id, project_id) VALUES (?, ?, ?, ?)
2024-07-25 20:39:20,748 INFO sqlalchemy.engine.Engine [generated in 0.00521s] [(0, 12, 12, 1), (1, 12, 35, 1), (2, 12, 42, 1), (3, 12, 70, 1), (4, 12, 381, 1), (5, 12, 60, 1), (6, 12, 48, 1), (7, 12, 725, 1)  ... displaying 10 of 5505 total bound parameter sets ...  (5503, 15603, 719, 1), (5504, 15606, 719, 1)]
2024-07-25 20:39:20,755 INFO sqlalchemy.engine.Engine COMMIT

/var/folders/qf/j616b9d53yn77zcpky42s5r40000gn/T/ipykernel_24964/945524614.py:12: SAWarning: relationship 'Code.code_type' will copy column code_types.type_id to column codes.type_id, which conflicts with relationship(s): 'CodeType.codes' (copies code_types.type_id to codes.type_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="codes"' to the 'Code.code_type' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
  session.bulk_insert_mappings(model, data) # type: ignore
/var/folders/qf/j616b9d53yn77zcpky42s5r40000gn/T/ipykernel_24964/945524614.py:12: SAWarning: relationship 'Element.segment' will copy column segments.segment_id to column elements.segment_id, which conflicts with relationship(s): 'Segment.elements' (copies segments.segment_id to elements.segment_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="elements"' to the 'Element.segment' relationship. (Background on this warning at: https://sqlalche.me/e/20/qzyx) (This warning originated from the `configure_mappers()` process, which was invoked automatically in response to a user-initiated operation.)
  session.bulk_insert_mappings(model, data) # type: ignore
/var/folders/qf/j616b9d53yn77zcpky42s5r40000gn/T/ipykernel_24964/945524614.py:9: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  data: list[dict[Hashable, Any]] = df.to_dict(orient='records') # type: ignore

In [6]:
# Step 1: Select a random code item
random_code = session.query(Code).order_by(func.random()).first()

if random_code:
    code_id = random_code.code_id
    print("Random Code ID:")
    print(code_id)
    print("Random Code Item:")
    print(random_code)

    # Step 2: Find all annotations associated with the selected code
    annotations = session.query(Annotation).filter(Annotation.code_id == code_id).all()

    if annotations:
        print('----\nRESULTS\n-----')
        for annotation in annotations:
            print("\nAssociated Annotation:")
            print(annotation)

            # Step 3: Retrieve all elements associated with those annotations
            element_id = annotation.element_id
            element = session.query(Element).filter(Element.element_id == element_id).first()

            if element:
                print("\nAssociated Element:")
                print(element)
            else:
                print("No associated elements found.")
            print("\n")
            print("--------------------------------------------------")
            print("\n")
    else:
        print("No associated annotations found.")
else:
    print("No codes found in the database.")

2024-07-25 20:39:20,763 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-07-25 20:39:20,766 INFO sqlalchemy.engine.Engine SELECT codes.code_id AS codes_code_id, codes.term AS codes_term, codes.description AS codes_description, codes.type_id AS codes_type_id, codes.reference AS codes_reference, codes.coordinates AS codes_coordinates, codes.project_id AS codes_project_id
FROM codes ORDER BY random()
 LIMIT ? OFFSET ?
2024-07-25 20:39:20,766 INFO sqlalchemy.engine.Engine [generated in 0.00058s] (1, 0)
Random Code ID:
175
Random Code Item:
Code(code_id=175, term=Tanakh, description=The canonical collection of Jewish texts, which is a significant part of the Christian Old Testament., type_id=4, reference=https://en.wikipedia.org/wiki/Tanakh, coordinates=None)
2024-07-25 20:39:20,769 INFO sqlalchemy.engine.Engine SELECT annotations.annotation_id AS annotations_annotation_id, annotations.element_id AS annotations_element_id, annotations.code_id AS annotations_code_id, annotations.project_id AS annotations_project_id
FROM annotations
WHERE annotations.code_id = ?
2024-07-25 20:39:20,769 INFO sqlalchemy.engine.Engine [generated in 0.00045s] (175,)
----
RESULTS
-----

Associated Annotation:
Annotation(annotation_id=364, element_id=227, code_id=175)
2024-07-25 20:39:20,770 INFO sqlalchemy.engine.Engine SELECT elements.element_id AS elements_element_id, elements.element_text AS elements_element_text, elements.segment_id AS elements_segment_id, elements.project_id AS elements_project_id
FROM elements
WHERE elements.element_id = ?
 LIMIT ? OFFSET ?
2024-07-25 20:39:20,771 INFO sqlalchemy.engine.Engine [generated in 0.00045s] (227, 1, 0)

Associated Element:
Element(element_id=227, element_text=Aimen Dean Indeed. But you see, in from the Islamic point of view, we see ourselves nothing as an extension of the New Testament, but as an extension of the Old Testament. So, the God of Islam is identical to the God of the Old Testament, of the Torah, of the Tanakh. You know, of the Jewish Tanakh. Rather than, you know, of the Christian New Testament, the Christian Bible. Because you see, in – in Islam, the relationship between the individual and the Creator are far more complex, for example, than the relationship between the individual and the Creator in Christianity. And Islam, it is based on love, fear, and hope while, in Christianity, it's solely based on love, so. , segment_id=1)


--------------------------------------------------